version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: OmniSharp.Extensions.LanguageClient
    versions:
    - 0.19.0
  - dependency-name: OmniSharp.Extensions.LanguageServer
    versions:
    - 0.18.3
    - 0.19.0
  - dependency-name: OmniSharp.Extensions.DebugAdapter.Server
    versions:
    - 0.19.0
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
